_about:
        pattern: /about/
        defaults: {_controller: VadimBlogBundle:Default:about}

_see:
        pattern: /see/{id}
        defaults: {_controller: VadimBlogBundle:Default:see}

_mostView:
        pattern: /mostView/
        defaults: {_controller: VadimBlogBundle:Default:mostView}

_lastArticles:
        pattern: /lastArticles/
        defaults: {_controller: VadimBlogBundle:Default:lastArticles}

_searchArticle:
        pattern: /searchArticle/
        defaults: {_controller: VadimBlogBundle:Default:searchArticle}

_tag:
        pattern: /tag/{id}
        defaults: {_controller: VadimBlogBundle:Default:tag}

_category:
        pattern: /category/{id}
        defaults: {_controller: VadimBlogBundle:Default:category}

_blog:
        pattern: /
        defaults: {_controller: VadimBlogBundle:Default:blog}

#_tagCloud:
#        pattern: /tagCloud/
#        defaults: {_controller: VadimBlogBundle:Default:tagCloud}

_showArticles:
        pattern: /showArticles/{page}
        defaults: {_controller: VadimBlogBundle:Default:showArticles, page: 1}

_resultSearch:
        pattern: /resultSearch/
        defaults: {_controller: VadimBlogBundle:Default:resultSearch}