_about:
        pattern: /about/
        defaults: {_controller: VadimBlogBundle:PageContent:about}

_see:
        pattern: /see/{id}
        defaults: {_controller: VadimBlogBundle:PageContent:see}

_searchArticle:
        pattern: /searchArticle/
        defaults: {_controller: VadimBlogBundle:PageContent:searchArticle}

_tag:
        pattern: /tag/{id}
        defaults: {_controller: VadimBlogBundle:PageContent:tag}

_category:
        pattern: /category/{id}
        defaults: {_controller: VadimBlogBundle:PageContent:category}

_blog:
        pattern: /
        defaults: {_controller: VadimBlogBundle:PageContent:blog}

_showArticles:
        pattern: /showArticles/{page}
        defaults: {_controller: VadimBlogBundle:PageContent:showArticles, page: 1}

_resultSearch:
        pattern: /resultSearch/
        defaults: {_controller: VadimBlogBundle:PageContent:resultSearch}


_mostViewArticles:
        pattern: /mostView/
        defaults: {_controller: VadimBlogBundle:Panel:mostViewArticles}

_lastArticles:
        pattern: /lastArticles/
        defaults: {_controller: VadimBlogBundle:Panel:lastArticles}

_lastPosts:
        pattern: /lastPosts/
        defaults: {_controller: VadimBlogBundle:Panel:lastPosts}

_tagCloud:
        pattern: /tagCloud/
        defaults: {_controller: VadimBlogBundle:Panel:tagCloud}
